### ISSUE TITLE
*Error handling* yang lebih baik

### ISSUE THREAD

**Issue by hangga** [tokopedia/Bug-Bounty#8]
Emm.. gimana ya. Boleh dianggap bug atau bukan, tapi sy sebagai user sptnya kurang nyaman.

**Step to reproduce**
 1. Pilih produk yang kurirnya diluar area/jangkauan.
 2. Klik tombol Beli
 3. Checkout -> Pilih Kurir

**Actual result:**
Pesan errornya `Gagal mengambil data`, namun lucunya ada tombol "Coba lagi" untuk merequest ulang. Padahal kalo direquest ulang seribu kali bahkan sejuta kali tetap hasilnya error 400 juga, karena kurir diluar jangkauan.
![response-wagu-700x394](https://user-images.githubusercontent.com/6803784/51733537-306a8480-20b4-11e9-9d03-c839bfe3454c.png)

**Endpoint request:** 
https://gw.tokopedia.com/v2/rates?callback=jQuery19108977403708117607_1539919319473&service=sameday&names=gojek,grab&origin=1603|15211|-6.096146500000001,106.6889122&weight=7&from=client&token=Tokopedia+Kero:TYnvROYwESCmZuhClHAchPXdhmg=&ut=1539919319&insurance=1&product_insurance=0&order_value=60000&cat_id=2083&lang=id&destination=3613|55173|-7.824337850304216,110.40123481303452&_=1539919319475

**response:**
```
{"errors":[{"id":"541","status":"400","title":"No data found."}]}
```

* Statusnya `400`, tapi titlenya `No data found`. Saya ndak tahu apakah tokopedia punya standarisasi code status sendiri.

* Setahu sy `400` itu umumnya seputar kesalahan request bisa karena salah parameter atau lainya.
Kalo `data not found` biasanya `404`. 

* Atau statusnya tetep `400`, tapi lebih baik pesannya diganti misalnya `Diluar jangkauan!` **agar user langsung tahu kesalahannya**.

Matur nuwun.

**Comment by endang121** [comment]
Gus siap

**Comment by endang121** [comment]
Coba untuk masuk ulang acun anda
